export default function randomFact(){
  const facts = [
      "Bananas are berries, but strawberries aren't.",
      "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.",
      "The Eiffel Tower can be 15 cm taller during the summer, as the heat expands the metal.",
      "An octopus has three hearts.",
      "A group of flamingos is called a flamboyance.",
      "The unicorn is the national animal of Scotland.",
      "There are more fake flamingos in the world than real ones.",
      "There are only two countries in the world that don't use the metric system: Liberia and Myanmar.",
      "The average person walks the equivalent of five times around the world in their lifetime.",
      "Octopuses have blue blood.",
      "Honey never spoils.",
      "There are more possible iterations of a game of chess than there are atoms in the known universe.",
      "Peanuts are not nuts; they are legumes.",
      "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.",
      "An ostrich's eye is bigger than its brain.",
    "Bananas are berries.",
      "Octopuses have three hearts.",
      "Honey never spoils.",
      "The shortest war in history lasted 38 minutes.",
      "A day on Venus is longer than a year.",
      "The Eiffel Tower can be 6 inches taller during the summer.",
      "Polar bears are left-handed.",
      "The world's oldest known recipe is for beer.",
      "Cows have best friends.",
      "The Great Wall of China is not visible from space.",
      "A group of flamingos is called a flamboyance.",
      "The average person will spend six months of their life waiting for red lights to turn green.",
      "The world's largest desert is Antarctica.",
      "The shortest complete sentence in English is 'I am.'",
      "The dot over the letter 'i' is called a tittle.",
      "The smell of freshly-cut grass is actually a plant distress call.",
      "The world's largest pizza was 13,580 square feet.",
      "The first recorded game of baseball was played in 1846.",
      "The world's smallest mammal is the bumblebee bat.",
      "The longest recorded flight of a chicken is 13 seconds.",
     "In an average NFL football game, there are only about 12 minutes of actual play time.",
      "If you started with $0.01 and doubled your money every day, it would take 27 days to become a millionaire.",
      "Baby robins eat an impressive 14 feet of earthworms every day.",
      "The biggest tapeworm found inside a human body was 35 meters long.",
      "A mix between a Chihuahua and a dachshund is called a 'chiweenie'.",
      "Surprisingly, there are no seagulls in Hawaii.",
      "Even though dragonflies have six legs, they can't walk.",
      "The world's largest desert is Antarctica.",
      "The dot over the letter 'i' is called a tittle.",
      "The smell of freshly-cut grass is actually a plant distress call."
  ];
    const randomIndex = Math.floor(Math.random() * facts.length);  
    return facts[randomIndex];
}
